config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  
  resources :rooms do
    collection do
      get 'my_rooms'
    end
  end

  resources :reservations, only: [:new, :create, :show, :index, :destroy]
  resource :account, only: [:show, :edit, :update]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container text-center mt-5">
  <h1 class="mb-4">ReservationApp</h1>
  <p class="lead">まだ体験したことのない旅をしよう。</p>

  <%= form_with url: rooms_path, method: :get, local: true, class: "mb-4" do %>
    <div class="row justify-content-center g-3">

      <div class="col-md-4">
        <%= label_tag :area, "", for: "area_field", class: "form-label" %>
        <%= text_field_tag :area, params[:area], id: "area_field", class: "form-control", placeholder: "エリア名を入力" %>
      </div>

      <div class="col-md-4 d-flex align-items-end">
        <%= submit_tag "検索", class: "btn btn-primary w-100" %>
      </div>
    </div>
  <% end %>

</div>

app/views/home/new.html.erb
<div class="container">
  <h2 class="my-4">新規ユーザー登録</h2>

  <%= form_with model: @user, url: user_registration_path, local: true do |f| %>
    <!-- 名前フィールド -->
    <div class="mb-3">
      <%= f.label :name, "名前", class: "form-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <!-- メールアドレスフィールド -->
    <div class="mb-3">
      <%= f.label :email, "メールアドレス", class: "form-label" %>
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <!-- パスワードフィールド -->
    <div class="mb-3">
      <%= f.label :password, "パスワード", class: "form-label" %>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <!-- パスワード確認フィールド -->
    <div class="mb-3">
      <%= f.label :password_confirmation, "パスワード確認", class: "form-label" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <!-- 登録ボタン -->
    <div>
      <%= f.submit "登録", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/home/show.html.erb
<div class="container">
  <h1 class="my-4">アカウントページ</h1>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">アカウント情報</h5>

      <p class="card-text">
        <strong>名前:</strong> <%= @user.name %><br>
        <strong>メールアドレス:</strong> <%= @user.email %><br>
        <strong>パスワード:</strong> *********
      </p>

      <%= link_to 'アカウント情報を編集', edit_user_registration_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>