config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  
  resources :rooms do
    collection do
      get 'my_rooms'
    end
  end

  resources :reservations, only: [:new, :create, :show, :index, :destroy]
  resource :account, only: [:show, :edit, :update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReservationApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <!-- ナビゲーションバー -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">ReservationApp</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= image_tag current_user.icon.attached? ? current_user.icon : 'default-avatar.png', class: 'icon-image', alt: 'User Icon' %>
              <%= current_user.email %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to '施設の新規登録', new_room_path, class: 'dropdown-item' %></li>
              <li><%= link_to '予約済み一覧', reservations_path, class: 'dropdown-item' %></li>
              <li><%= link_to '登録済み一覧', my_rooms_rooms_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'アカウント設定', account_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to '新規登録', new_user_registration_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


  <!-- フラッシュメッセージ -->
  <div class="container mt-3">
    <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>
  </div>

  <!-- メインコンテンツ -->
  <div class="container">
    <%= yield %>
  </div>
  
</body>
</html>