config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  
  resources :rooms do
    collection do
      get 'my_rooms'
    end
  end

  resources :reservations, only: [:new, :create, :show, :index, :destroy]
  resource :account, only: [:show, :edit, :update]
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(account_params)
      redirect_to account_path, notice: 'アカウント情報が更新されました。'
    else
      render :edit
    end
  end

  private

  def account_params
    if params[:user][:password].blank?
      params.require(:user).permit(:email, :name, :bio, :icon)
    else
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :bio, :icon)
    end
  end
end

app/views/accounts/edit.html.erb
<div class="container">
  <h1>アカウント設定の編集</h1>

  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="#account" data-bs-toggle="tab">アカウント</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#profile" data-bs-toggle="tab">プロフィール</a>
    </li>
  </ul>

  <div class="tab-content">
    <!-- アカウントタブ -->
    <div id="account" class="tab-pane fade show active">
      <%= form_for current_user, url: account_path, method: :patch, html: { multipart: true } do |f| %>
        <div class="mb-3">
          <%= f.label :email, "メールアドレス" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :current_password, "現在のパスワード" %>
          <%= f.password_field :current_password, class: "form-control", placeholder: "現在のパスワード" %>
        </div>

        <div class="mb-3">
          <%= f.label :password, "変更後のパスワード" %>
          <%= f.password_field :password, class: "form-control", placeholder: "新しいパスワード" %>
        </div>

        <div class="mb-3">
          <%= f.label :password_confirmation, "確認用パスワード" %>
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "新しいパスワードの再入力" %>
        </div>

        <%= f.submit "保存", class: "btn btn-success" %>
      <% end %>
    </div>

    <!-- プロフィールタブ -->
    <div id="profile" class="tab-pane fade">
      <%= form_for current_user, url: account_path, method: :patch, html: { multipart: true } do |f| %>
        <div class="mb-3">
          <%= f.label :name, "名前" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :bio, "自己紹介" %>
          <%= f.text_area :bio, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :icon, "プロフィール画像" %>
          <%= f.file_field :icon, class: "form-control" %>
          <% if current_user.icon.attached? %>
            <%= image_tag current_user.icon %>
          <% else %>
            <%= image_tag 'default-avatar.png', class: 'img-fluid' %> <!-- デフォルト画像を表示 -->
          <% end %>
        </div>

        <%= f.submit "保存", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="container">
  <h1>アカウント設定</h1>
  
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="#account" data-bs-toggle="tab">アカウント</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#profile" data-bs-toggle="tab">プロフィール</a>
    </li>
    <li class="nav-item ms-auto">
      <%= link_to '<i class="bi bi-pencil"></i> 編集'.html_safe, edit_account_path, class: "btn btn-primary" %>
    </li>
  </ul>

  <div class="tab-content">
    <div id="account" class="tab-pane fade show active">
      <p>メール: <%= current_user.email %></p>
      <p>パスワード: <%= '*' * 8 %></p>
    </div>
    <div id="profile" class="tab-pane fade">
      <p>ユーザー名: <%= current_user.name %></p>
      <p>自己紹介: <%= current_user.bio %></p>
      
      <% if current_user.icon.attached? %>
        <%= image_tag current_user.icon %>
      <% else %>
        <%= image_tag 'default-avatar.png' %>
      <% end %>
    </div>
  </div>
</div>